language: scala
sudo: false
scala:
  - 2.11.8
jdk:
  - oraclejdk8
services:
  - mongodb
script:
  - bin/travis.sh
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
  # Delete any SBT lock files
  - find $HOME/.sbt -name "*.lock" -delete
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
notifications:
  email: false